import json
import requests
from io import BytesIO
from PIL import Image
from ebooklib import epub
import math


def fetch_image_bytes(url, max_width=400):
    headers = {
        "User-Agent": (
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
            "AppleWebKit/537.36 (KHTML, like Gecko) "
            "Chrome/117.0.0.0 Safari/537.36"
        )
    }
    try:
        response = requests.get(url, headers=headers, timeout=10)
        response.raise_for_status()
        img = Image.open(BytesIO(response.content))
        width, height = img.size
        ratio = min(max_width / width, 1)
        img = img.resize((int(width * ratio), int(height * ratio)))
        buffer = BytesIO()
        img.save(buffer, format="PNG")
        return buffer.getvalue()
    except Exception as e:
        print(f"Could not load image {url}: {e}")
        return None


def build_answer_table_html(all_questions, cols=5):
    """
    Build an HTML table showing question number and correct choices.
    """
    answers = []
    for i, data in enumerate(all_questions, start=1):
        correct_choices = data.get("correct_choices", [])
        answer_text = ", ".join(correct_choices)
        answers.append(f"{i}. {answer_text}")

    rows = math.ceil(len(answers) / cols)
    table_html = "<table class='answer-table'>"
    for r in range(rows):
        table_html += "<tr>"
        for c in range(cols):
            idx = r * cols + c
            if idx < len(answers):
                table_html += f"<td>{answers[idx]}</td>"
            else:
                table_html += "<td></td>"
        table_html += "</tr>"
    table_html += "</table>"
    return table_html


def jsonl_to_epub(jsonl_file, epub_file, group_size=10):
    book = epub.EpubBook()
    book.set_identifier("exam-questions")
    book.set_title("Question Collection")
    book.set_language("en")
    book.add_author("Generated by ChatGPT")

    css_style = """
    body { font-family: Arial, sans-serif; }
    h2 { font-weight: bold; margin-top: 1.2em; }
    p { margin: 0.5em 0; }
    .choice { margin-left: 1em; }
    img { margin: 0.5em 0; max-width: 100%; height: auto; }
    hr { border: none; border-top: 1px solid #999; margin: 1em 0; }
    table.answer-table {
        border-collapse: collapse;
        width: 100%;
        margin-top: 1em;
        font-size: 0.9em;
    }
    table.answer-table td {
        border: 1px solid #aaa;
        padding: 4px 6px;
        vertical-align: middle;
    }
    """
    style_item = epub.EpubItem(
        uid="style_nav",
        file_name="style/style.css",
        media_type="text/css",
        content=css_style,
    )
    book.add_item(style_item)

    # Read all questions first
    with open(jsonl_file, "r", encoding="utf-8") as f:
        all_questions = [json.loads(line) for line in f]

    chapters = []
    total = len(all_questions)

    # === Question Chapters ===
    for start in range(0, total, group_size):
        end = min(start + group_size, total)
        group = all_questions[start:end]

        html_content = ""
        for i, data in enumerate(group, start=start + 1):
            html_content += f"<h2>{data.get('question_no', f'Question {i}')}</h2>"

            # Question text
            for paragraph in data.get("text", []):
                html_content += f"<p>{paragraph}</p>"

            # Images
            for j, img_url in enumerate(data.get("img", [])):
                img_bytes = fetch_image_bytes(img_url)
                if img_bytes:
                    img_name = f"images/img_{i}_{j}.png"
                    img_item = epub.EpubItem(
                        uid=f"img_{i}_{j}",
                        file_name=img_name,
                        media_type="image/png",
                        content=img_bytes,
                    )
                    book.add_item(img_item)
                    html_content += f'<p><img src="{img_name}" alt="image"/></p>'

            # Choices
            if data.get("choices"):
                html_content += "<ul>"
                for choice in data["choices"]:
                    html_content += f"<li class='choice'>{choice}</li>"
                html_content += "</ul>"

            html_content += "<hr/>"

        chapter_no = start // group_size + 1
        chapter_title = f"Questions {start + 1}–{end}"
        chapter = epub.EpubHtml(
            title=chapter_title,
            file_name=f"chapter_{chapter_no}.xhtml",
            lang="en",
            content=html_content,
        )
        chapter.add_item(style_item)
        book.add_item(chapter)
        chapters.append(chapter)

    # === Answer Sheet Chapter ===
    answer_table_html = build_answer_table_html(all_questions, cols=5)
    answer_html = f"""
    <h2>Answer Sheet</h2>
    <p>This section lists all correct answers in a fixed-width table.</p>
    {answer_table_html}
    """
    answer_chapter = epub.EpubHtml(
        title="Answer Sheet",
        file_name="answers.xhtml",
        lang="en",
        content=answer_html,
    )
    answer_chapter.add_item(style_item)
    book.add_item(answer_chapter)
    chapters.append(answer_chapter)

    # === TOC & Navigation ===
    book.toc = tuple(chapters)
    book.spine = ["nav"] + chapters

    book.add_item(epub.EpubNcx())
    book.add_item(epub.EpubNav())

    epub.write_epub(epub_file, book)
    print(f"✅ EPUB generated successfully: {epub_file}")


if __name__ == "__main__":
    jsonl_file = "output.jsonl"
    epub_file = "questions_with_answers.epub"
    jsonl_to_epub(jsonl_file, epub_file, group_size=10)
